### PR TITLE
webpackの軽量化

### PR DESCRIPTION
**Pull request by nobuhiko**

### CODE REVIEW

**Comment by nanasess** [comment]
Copilot actions による説明

This pull request focuses on modernizing the JavaScript codebase by switching from CommonJS to ES6 module syntax, updating dependencies, and improving code formatting for better readability and maintainability. The most important changes include updating imports, upgrading dependencies, and enhancing code formatting.

### Modernization and Dependency Updates:

* **Switch from CommonJS to ES6 Modules**: Replaced `require` statements with `import` statements for better compatibility with modern JavaScript standards in `data/eccube.js`.
* **Dependency Updates**: Updated several dependencies in `package.json` to their latest versions, including `jquery` to `3.7.1` and `jquery-migrate` to `3.5.2`.

### Code Formatting Improvements:

* **Consistent Code Formatting**: Improved code formatting by adding line breaks and indentation for better readability in multiple sections of `data/eccube.js`. [[1]](diffhunk://#diff-5798b5605699494f3735bef15f0bf6171130382f50b949dedb129bb96cd6e792L70-R66) [[2]](diffhunk://#diff-5798b5605699494f3735bef15f0bf6171130382f50b949dedb129bb96cd6e792L112-R121) [[3]](diffhunk://#diff-5798b5605699494f3735bef15f0bf6171130382f50b949dedb129bb96cd6e792L148-R160)
* **Trailing Comma Addition**: Added trailing commas in object literals and function parameters to adhere to modern JavaScript coding standards in `data/eccube.js`. [[1]](diffhunk://#diff-5798b5605699494f3735bef15f0bf6171130382f50b949dedb129bb96cd6e792L59-R56) [[2]](diffhunk://#diff-5798b5605699494f3735bef15f0bf6171130382f50b949dedb129bb96cd6e792L331-R356)

### Build Configuration:

* **Webpack Configuration Update**: Added `TerserPlugin` to the `webpack.config.js` for better minification and optimization of the production build.

**Comment by nanasess** [comment]
@nobuhiko 
`yarn install --frozen-lockfile` を実行すると、以下のようなエラーになります。
```
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```
package.json で  `"packageManager": "yarn@1.22.22..."` としているためだと思われますが、以下どうしましょうかね。
1. corepack の利用をやめる
2. yarn v1 形式の yarn.lock にする

**Comment by nobuhiko** [comment]
あー、yarnのバージョンが合ってないのか
やっぱyarnやめちゃいたいですね

**Comment by nanasess** [comment]
yarn やめても問題ないと思うんですが、いきなりやめると少々混乱しそうです。
一定期間共存できたりしないですかね🤔

**Review by nanasess — APPROVED** [review]
LGTM

**Pull request merged**
